# Regional SSL certificate
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSSLCertificate
metadata:
  name: jitaccess-regional-ssl-cert
spec:
  location: northamerica-northeast1
  description: Regional ssl cert for the jitaccess app LB
  certificate:
    valueFrom:
      secretKeyRef:
        name: jitaccess-regional-ssl-data
        key: certificate
  privateKey:
    valueFrom:
      secretKeyRef:
        name: jitaccess-regional-ssl-data
        key: privateKey
---
apiVersion: v1
kind: Secret
metadata:
  name: jitaccess-regional-ssl-data
stringData:
  certificate: projects/142631071295/secrets/jitaccess-ssl-cert-reg/versions/1
  privateKey: projects/142631071295/secrets/jitaccess-ssl-pk-reg/versions/1
