# Multi party approval secret
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: jitaccess-mpa-secret-manager
spec:
  replication:
    userManaged:
      replicas:
        - location: northamerica-northeast1
